### ISSUE TITLE
Unable to run this plugin

### ISSUE THREAD

**Issue by edo2313** [PseudoResonance/InfinityMendingUnnerf#1]
Hello. I was trying to run this plugin on my papermc server and I got the error below. 

`[InfinityMendingUnnerf] Enabling InfinityMendingUnnerf v1.2.2
[10:52:32 INFO]: Loading in Minecraft 1.16
[10:52:32 INFO]: Minecraft 1.11 or later.
[10:52:32 INFO]: Running Java 8 or older!
[10:52:32 INFO]: Running JRE!
[10:52:32 INFO]: If using JRE, please place tools.jar at: /PATHREDACTED/plugins/InfinityMendingUnnerf/tools.jar
[10:52:32 INFO]: If using JRE, please place attach.dll or attach.so in directory: /PATHREDACTED/plugins/InfinityMendingUnnerf
[10:52:32 INFO]: Current Java library path: /PATHREDACTED/plugins/InfinityMendingUnnerf:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[10:52:32 INFO]: Current JNA library path: /PATHREDACTED/plugins/InfinityMendingUnnerf
[10:52:32 ERROR]: Failed to initialize attach.dll/attach.so!
[10:52:32 WARN]: java.lang.NullPointerException
[10:52:32 WARN]: at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
[10:52:32 WARN]: at java.lang.Runtime.loadLibrary0(Runtime.java:871)
[10:52:32 WARN]: at java.lang.System.loadLibrary(System.java:1124)
[10:52:32 WARN]: at io.github.pseudoresonance.infinitymendingunnerf.Unnerf.onEnable(Unnerf.java:65)
[10:52:32 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:52:32 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[10:52:32 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[10:52:32 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500)
[10:52:32 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414)
[10:52:32 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[10:52:32 WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[10:52:32 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[10:52:32 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[10:52:32 WARN]: at java.lang.Thread.run(Thread.java:748)
[10:52:32 INFO]: Loading injector!
[10:52:32 ERROR]: Error occurred while enabling InfinityMendingUnnerf v1.2.2 (Is it up to date?)
java.lang.IllegalStateException: No compatible attachment provider is available
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:597) ~[?:?]
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:581) ~[?:?]
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:533) ~[?:?]
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:510) ~[?:?]
at io.github.pseudoresonance.infinitymendingunnerf.Unnerf.onEnable(Unnerf.java:76) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[10:52:32 INFO]: [InfinityMendingUnnerf] Disabling InfinityMendingUnnerf v1.2.2`

I obviously checked which version of Java I was using because of this error and I got this, so I have JDK 8...
`openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)`

How can I troubleshoot further?

**Comment by PseudoResonance** [comment]
Please run `javac -version` to see if you have the compiler. I am assuming you are running the OpenJDK JRE, not the JDK. OpenJDK is the name of a project that replaces Oracle's Java, but there are both JDK and JRE versions of OpenJDK. You are likely running a JRE version that is missing the JDK, meaning you are also missing the java compiler and attach.dll/attach.so.

**Comment by edo2313** [comment]
Oh ok, now I see, my bad. I indeed have the OpenJDK JRE, not the JDK, and I somehow thought that there wasn't a JRE-only version of it. Thanks for the clarification :)

Have a nice day!
