### ISSUE TITLE
IllegalStateException: Error during attachment

### ISSUE THREAD

**Issue by rushiiMachine** [PseudoResonance/InfinityMendingUnnerf#2]
Using PaperMC 1.16.3 #264
Using Java 8 JRE + JDK's tools.jar & attach.dll moved into the appropriate folder

```
[18:25:37] [Server thread/INFO]: [InfinityMendingUnnerf] Enabling InfinityMendingUnnerf v1.2.2
[18:25:37 INFO]: Loading in Minecraft 1.16
[18:25:37 INFO]: Minecraft 1.11 or later.
[18:25:37 INFO]: Running Java 8 or older!
[18:25:37 INFO]: Running JRE!
[18:25:37 INFO]: Current Java library path: C:\Users\[redacted]\Desktop\PCMSMC\plugins\InfinityMendingUnnerf;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\Git LFS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Programs\ffmpeg-4.2.3-win64-static\bin;C:\Programs;C:\Users\[redacted]\AppData\Local\Programs\Microsoft VS Code;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Program Files\dotnet\;C:\Users\[redacted]\.windows-build-tools\python27\;C:\Users\[redacted]\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\[redacted]\AppData\Local\Programs\Python\Python38-32\;C:\Users\[redacted]\AppData\Local\Microsoft\WindowsApps;C:\Users\[redacted]\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\[redacted]\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.4\bin;C:\Users\[redacted]\AppData\Roaming\npm;C:\Program Files\OpenSSL-Win64\bin;C:\Users\[redacted]\.dotnet\tools;C:\Users\[redacted]\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\bin;C:\Users\[redacted]\.dotnet\tools;.
[18:25:37 INFO]: Current JNA library path: C:\Users\[redacted]\Desktop\PCMSMC\plugins\InfinityMendingUnnerf
[18:25:37 INFO]: Initialized attach.dll!
[18:25:37 INFO]: Loading injector!
[18:25:37 WARN]: java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated
[18:25:37 ERROR]: Error occurred while enabling InfinityMendingUnnerf v1.2.2 (Is it up to date?)
java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@5f1b72d3
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:581) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:533) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:510) ~[?:?]
        at io.github.pseudoresonance.infinitymendingunnerf.Unnerf.onEnable(Unnerf.java:76) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at net.bytebuddy.agent.Attacher.install(Attacher.java:106) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:603) ~[?:?]
        ... 14 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:203) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202]
        at net.bytebuddy.agent.Attacher.install(Attacher.java:106) ~[?:?]
        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:603) ~[?:?]
        ... 14 more
[18:25:37] [Server thread/INFO]: [InfinityMendingUnnerf] Disabling InfinityMendingUnnerf v1.2.2
```

**Comment by PseudoResonance** [comment]
Sorry, I tried my best to figure out a way of loading in the attachment provider even in a JRE, but I wasn't able to figure it out. Unless someone else can come up with a solution to this, I don't think it'll be possible to run this plugin on a Java 8 or older JRE. I realize a lot of people are still running Java 8 for Minecraft, but honestly, given how old it is, I don't really feel like it's worth investing more time into supporting.

The solution should be to move to a newer version of Java, not to keep making do with a version of Java that came out in 2014.

If you can, update to Java 9 or later, or at least install Java 8 JDK. It will work out of the box on those. Or if you're insistent on making it work on Java 8 JRE, I guess feel free to fiddle with it and try to find a solution, but I spent several hours researching and messing with it and never got it working.

Also, if you've already got Java 8 JDK and you're still having this problem, make sure you're actually running the server on it. You might want to change the environment variables to make it the default.

**Comment by rushiiMachine** [comment]
Thank you!
I changed my path to use jdk 8, works perfectly.
