### ISSUE TITLE
Server.pro, MC 1.17 - java.lang.NoSuchFieldException: sys_paths

### ISSUE THREAD

**Issue by WillyJL** [PseudoResonance/InfinityMendingUnnerf#7]
Can't seem to get this to work :/
Hosting: server.pro, 2GB ram - 20GB storage - 2 vCores
MC: Spigot 1.17

```
[InfinityMendingUnnerf] Enabling InfinityMendingUnnerf v1.2.4
[InfinityMendingUnnerf] Loading in Minecraft 1.17
[InfinityMendingUnnerf] Minecraft 1.11 or later.
[InfinityMendingUnnerf] Running Java 8 or older!
[InfinityMendingUnnerf] Running JRE!
[InfinityMendingUnnerf] If using JRE, please place tools.jar at: /home/gs-40395/plugins/InfinityMendingUnnerf/tools.jar
[InfinityMendingUnnerf] If using JRE, please place attach.dll or attach.so in directory: /home/gs-40395/plugins/InfinityMendingUnnerf
[InfinityMendingUnnerf] Failed to initialize attach.dll/attach.so!
java.lang.NoSuchFieldException: sys_paths
	at java.base/java.lang.Class.getDeclaredField(Unknown Source)
	at io.github.pseudoresonance.infinitymendingunnerf.Unnerf.onEnable(Unnerf.java:66)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608)
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
	at java.base/java.lang.Thread.run(Unknown Source)
[InfinityMendingUnnerf] Loading injector!
Error occurred while enabling InfinityMendingUnnerf v1.2.4 (Is it up to date?)
java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@4179ef3f
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515) ~[?:?]
	at io.github.pseudoresonance.infinitymendingunnerf.Unnerf.onEnable(Unnerf.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.bytebuddy.agent.Attacher.install(Attacher.java:106) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608) ~[?:?]
	... 14 more
Caused by: java.lang.IllegalStateException: Target VM did not respond: 6
	at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$Factory$ForSocketFile.connect(VirtualMachine.java:541) ~[?:?]
	at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:256) ~[?:?]
	at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:243) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.bytebuddy.agent.Attacher.install(Attacher.java:106) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608) ~[?:?]
	... 14 more
```
Note: `plugins/InfinityMendingUnnerf` is empty, I would try putting that `attach.so` and `tools.jar` in there but I don't know where to find those files...

**Comment by WillyJL** [comment]
I know nothing about java and what jdk an jre are but saw that another closed issue had a similar error so ima add this in case it helps:
```
##########################################################################
#                          Java Version Checker                          #
#                                                                        #
#                    BEGIN JAVA/SYSTEM SPECIFICATIONS                    #
#                                                                        #
##########################################################################
java.specification.version:  16
sun.jnu.encoding:  UTF-8
java.class.path:  spigot-1.17.jar
java.vm.vendor:  AdoptOpenJDK
sun.arch.data.model:  64
jna.library.path:  /home/gs-40395/plugins/InfinityMendingUnnerf
sun.font.fontmanager:  sun.awt.X11FontManager
java.vendor.url:  https://adoptopenjdk.net/
user.timezone:  Europe/Paris
java.vm.specification.version:  16
os.name:  Linux
sun.java.launcher:  SUN_STANDARD
net.bytebuddy.agent.toolsjar:  /home/gs-40395/plugins/InfinityMendingUnnerf/tools.jar
sun.boot.library.path:  /pro/bin/java/java16-hotspot/lib
sun.java.command:  spigot-1.17.jar
jdk.debug:  release
sun.cpu.endian:  little
io.netty.eventLoopThreads:  4
user.home:  /home/gs-40395
user.language:  en
java.specification.vendor:  Oracle Corporation
java.version.date:  2021-04-20
java.home:  /pro/bin/java/java16-hotspot
file.separator:  /
java.vm.compressedOopsMode:  32-bit
line.separator:  
java.specification.name:  Java Platform API Specification
java.vm.specification.vendor:  Oracle Corporation
sun.management.compiler:  HotSpot 64-Bit Tiered Compilers
java.runtime.version:  16.0.1+9
user.name:  gs-40395
path.separator:  :
os.version:  4.15.0-106-generic
java.runtime.name:  OpenJDK Runtime Environment
file.encoding:  UTF-8
jnidispatch.path:  /home/gs-40395/.cache/JNA/temp/jna2299234505196872976.tmp
java.vm.name:  OpenJDK 64-Bit Server VM
jna.platform.library.path:  /usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib64:/usr/lib:/lib:/usr/lib/x86_64-linux-gnu/libfakeroot
java.vendor.version:  AdoptOpenJDK-16.0.1+9
jna.loaded:  true
java.vendor.url.bug:  https://github.com/AdoptOpenJDK/openjdk-support/issues
java.io.tmpdir:  /tmp
java.version:  16.0.1
user.dir:  /home/gs-40395
os.arch:  amd64
java.vm.specification.name:  Java Virtual Machine Specification
java.library.path:  /home/gs-40395/plugins/InfinityMendingUnnerf:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.vm.info:  mixed mode, sharing
java.vendor:  AdoptOpenJDK
java.vm.version:  16.0.1+9
sun.io.unicode.encoding:  UnicodeLittle
java.class.version:  60.0
##########################################################################
#                          Java Version Checker                          #
#                                                                        #
#                     END JAVA/SYSTEM SPECIFICATIONS                     #
#                                                                        #
##########################################################################
```

**Comment by PseudoResonance** [comment]
Thank you for the report. Would you please try [this build of InfinityMendingUnnerf](https://github.com/PseudoResonance/InfinityMendingUnnerf/files/6663448/InfinityMendingUnnerf-1.2.5.jar.zip)?

It sounds like perhaps your host is running a really, really stripped down version of Java, but I am hoping that maybe it was just a bug in the Java version detection that caused the issue.

**Comment by WillyJL** [comment]
Thanks for the reply!
First problem with `sys_paths` is gone but the main issue is still here :/
```
[18:08:13] [Server thread/INFO]: [InfinityMendingUnnerf] Enabling InfinityMendingUnnerf v1.2.5
[18:08:13] [Server thread/INFO]: [InfinityMendingUnnerf] Loading in Minecraft 1.17
[18:08:13] [Server thread/INFO]: [InfinityMendingUnnerf] Minecraft 1.11 or later.
[18:08:13] [Server thread/INFO]: [InfinityMendingUnnerf] Java: 16.0.1
[18:08:13] [Server thread/INFO]: [InfinityMendingUnnerf] Running Java 9 or newer!
[18:08:13] [Server thread/INFO]: [InfinityMendingUnnerf] Loading injector!
[18:08:15] [Server thread/ERROR]: Error occurred while enabling InfinityMendingUnnerf v1.2.5 (Is it up to date?)
java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@61bb1f5b
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515) ~[?:?]
	at io.github.pseudoresonance.infinitymendingunnerf.Unnerf.onEnable(Unnerf.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.bytebuddy.agent.Attacher.install(Attacher.java:106) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608) ~[?:?]
	... 14 more
Caused by: java.lang.IllegalStateException: Target VM did not respond: 6
	at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$Factory$ForSocketFile.connect(VirtualMachine.java:541) ~[?:?]
	at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:256) ~[?:?]
	at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:243) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.bytebuddy.agent.Attacher.install(Attacher.java:106) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608) ~[?:?]
	... 14 more
```
If it helps this is what Java options are provided in the dashboard:
![image](https://user-images.githubusercontent.com/49810075/122255339-4e77f000-cece-11eb-9570-290777447800.png)
And this is the rest of the "Advanced Settings":
![image](https://user-images.githubusercontent.com/49810075/122255430-6485b080-cece-11eb-907e-8809ba7f757f.png)

**Comment by PseudoResonance** [comment]
Can you try adding `--add-modules jdk.attach` to the start parameters? If you don't know where to put it, just put it before `-jar spigot-1.17.jar`

Something like `-server -Xms1024M -Xmx1024M -XX:-UsePerfData --add-modules jdk.attach -jar spigot-1.17.jar`

**Comment by WillyJL** [comment]
😭 
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.attach not found
```

**Comment by PseudoResonance** [comment]
To preface this, Java generally comes in 2 forms, a JRE (Java Runtime Environment) or a JDK (Java Development Kit). The JRE is included inside the JDK, and by downloading just the JRE, many unimportant modules are left out to save some space, including the "jdk.attach" module that is needed by this plugin.

That makes sense. It seems that AdoptOpenJDK's JRE doesn't include the jdk.attach module that is required in order to do bytecode manipulation and change the game code like that. I'd recommend opening a support ticket, explaining that this plugin needs the jdk.attach module, and asking if they could add another Java option to use the JDK from AdoptOpenJDK, or consider moving all their clients to the JDK instead of the JRE or something.

It's definitely a stretch, but as far as I am aware, it shouldn't pose any security risk to them, or cost them extra money or anything, as the additional space used by the JDK is fairly minimal. Although the statistics are heavily biased, from my [bstats page](https://bstats.org/plugin/bukkit/InfinityMendingUnnerf/8021), it seems like many hosts are already using the JDK anyways, making Server.pro the outlier, so hopefully they will understand and will switch over, although don't expect it to happen instantly.

As an example, [here's the AdoptOpenJDK download page](https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot). You can see on the right of the page, the different JDK and JRE downloads, and the size differences between them.

**Comment by WillyJL** [comment]
Alright thanks for the detailed explanation and sorry for the trouble :D
I've submitted a support message to server.pro for now and I'm closing this since it's unrelated to the plugin itself

**Comment by PseudoResonance** [comment]
I tried emailing them as well, explaining the situation, and they replied with
```
Thank you for contacting us today regarding this.

I have brought this up with our team so they are able to look into
this further for you!

Let me know if you have any more questions or issues.
```
Hopefully that means they'll switch over someday.
