### ISSUE TITLE
Can never get this to work for some reason.

### ISSUE THREAD

**Issue by ghost** [PseudoResonance/InfinityMendingUnnerf#9]
I am having troubles getting this plugin to work. I am running java 17 and I read that should work. here is the full log if you need more details. Anything I am doing wrong?
[REDACTED]
```
[16:58:31] [Server thread/INFO]: [InfinityMendingUnnerf] Enabling InfinityMendingUnnerf v1.2.5
[16:58:31] [Server thread/INFO]: [InfinityMendingUnnerf] Loading in Minecraft 1.18
[16:58:31] [Server thread/INFO]: [InfinityMendingUnnerf] Minecraft 1.11 or later.
[16:58:31] [Server thread/INFO]: [InfinityMendingUnnerf] Java: 61.0
[16:58:31] [Server thread/INFO]: [InfinityMendingUnnerf] Running Java 9 or newer!
[16:58:31] [Server thread/INFO]: [InfinityMendingUnnerf] Loading injector!
[16:58:31] [Server thread/ERROR]: Error occurred while enabling InfinityMendingUnnerf v1.2.5 (Is it up to date?)
java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@6c80f92a
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	at io.github.pseudoresonance.infinitymendingunnerf.Unnerf.onEnable(Unnerf.java:91) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-"78999b5"]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-"78999b5"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-"78999b5"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-"78999b5"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-"78999b5"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-"78999b5"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"78999b5"]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.io.IOException: Cannot run program "/usr/local/pebblej17/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1141) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1072) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:674) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:606) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	... 15 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:313) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:244) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1108) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1072) ~[?:?]
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:674) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:606) ~[InfinityMendingUnnerf-1.2.5.jar:?]
	... 15 more
[16:58:31] [Server thread/INFO]: [InfinityMendingUnnerf] Disabling InfinityMendingUnnerf v1.2.5
```

**Comment by PseudoResonance** [comment]
Please make sure to check your logs for any private information before posting them. Especially user login/logoff messages. I updated the message with just the relevant information.
That is a very strange error though. If possible, just to avoid the trouble for both of us, I'd recommend switching your server to Purpur instead of Paper. It's a fork of Paper, but it should, in theory, perform better, and it also has an option in the config file to allow mending and infinity together. It's guaranteed to work better than any plugin can do. Of course, if you can't run Purpur for some reason, I'll try taking a look to see what went wrong.

**Comment by TheCrafter8000** [comment]
I can confirm that this is an issue on my server as well. I can't get this to work on 1.18.1 paper. This is a nice plugin and there is no other plugin that has this feature, and I would like this issue to be fixed soon.

**Comment by PseudoResonance** [comment]
Do you have any error logs or anything?

**Comment by TheCrafter8000** [comment]
I get the same thing he is getting. The plugin wont load

**Comment by PseudoResonance** [comment]
You have the same "Caused by: java.io.IOException: Cannot run program "/usr/local/pebblej17/bin/java": error=2, No such file or directory"? Are you on PebbleHost? What's the exact error?

**Comment by TheCrafter8000** [comment]
I get the same exact error. After testing the plugin on a private server ran on my computer as well, I realized that it works fine on there. It must be something with pebblehost, so ill have to contact them

**Comment by TheCrafter8000** [comment]
I have contacted pebblehost. One of the staff says "It shouldn't need access to its own Java instance, it should be able to share java with the jar like all other plugins, especially for a plugin so simple"

**Comment by Vuurstergaming** [comment]
i have the same issue, also on pebblehost 17, is a fix in the works for this?

**Comment by PseudoResonance** [comment]
No, Pebblehost is doing something strange. It doesn't make sense that they're the only host it doesn't seem to work on. There are even safer ways to do this than the plugin though. I'd recommend using Purpur instead of Paper. It's basically a custom build of Paper that includes stuff like this, and it's easily configurable.

**Comment by MostlyLucid** [comment]
Having the same problem on a self hosted server, using 1.19.2 on paper. Any idea why this might be happening?
